# Generated by Django 3.2 on 2022-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=50)),
                ('industry_type', models.CharField(choices=[('', 'Select industry type'), ('Computer Industry', 'Computer Industry'), ('Chemical Industries', 'Chemical Industries'), ('Health Services', 'Health Services'), ('Telecommunications Services', 'Telecommunications Services'), ('Textiles: Clothing, Footwear', 'Textiles: Clothing, Footwear')], max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=150)),
                ('employee', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=150, unique=True)),
                ('since', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Crm Companies',
            },
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/contact')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('lead_score', models.IntegerField()),
                ('tags', models.CharField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/leads')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('lead_score', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=150)),
                ('tags', models.CharField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=13)),
                ('create_date', models.DateField()),
            ],
        ),
    ]
