# Generated by Django 3.2 on 2023-01-04 06:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcontact',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exiting', 'Exiting'), ('Lead', 'Lead'), ('Long-term', 'Long-term'), ('Partner', 'Partner')], max_length=50),
        ),
    ]
