# Generated by Django 3.2 on 2023-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20230105_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product', models.CharField(choices=[('Puma Tshirt', 'Puma Tshirt'), ('Adidas Sneakers', 'Adidas Sneakers'), ('350 ml Glass Grocery Container', '350 ml Glass Grocery Container'), ('American egale outfitters Shirt', 'American egale outfitters Shirt'), ('Galaxy Watch4', 'Galaxy Watch4'), ('Apple iPhone 12', 'Apple iPhone 12'), ('Funky Prints T-shirt', 'Funky Prints T-shirt'), ('USB Flash Drive Personalized with 3D Print', 'USB Flash Drive Personalized with 3D Print'), ('Oxford Button-Down Shirt', 'Oxford Button-Down Shirt'), ('Classic Short Sleeve Shirt', 'Classic Short Sleeve Shirt'), ('Half Sleeve T-Shirts (Blue)', 'Half Sleeve T-Shirts (Blue)'), ('Noise Evolve Smartwatch', 'Noise Evolve Smartwatch')], max_length=150)),
                ('order_date', models.DateTimeField()),
                ('amount', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('COD', 'COD'), ('Paypal', 'Paypal')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Cancelled', 'Cancelled'), ('Pickups', 'Pickups'), ('Returns', 'Returns'), ('Delivered', 'Delivered')], max_length=30)),
            ],
        ),
    ]
