# Generated by Django 3.2 on 2023-01-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_ecommerceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Block', 'Block')], max_length=12)),
            ],
        ),
    ]
