# Generated by Django 3.2 on 2023-01-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_ecommercecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(max_length=100)),
                ('assign_to', models.CharField(max_length=150)),
                ('create_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Inprogress', 'Inprogress'), ('New', 'New'), ('Open', 'Open')], max_length=10)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
            ],
        ),
    ]
